### ISSUE TITLE
Releasing Matomo 4.0 for Debian

### ISSUE THREAD

**Issue by aureq** [matomo-org/matomo-package#122] opened 2020-12-04 12:19 UTC
Matomo 4 requires at least `php-7.2.5` which is only available in Debian 10 Buster (the current stable).

Debian 9 Stretch (old stable) only offers `php-7.0` and was maintained (security updates) until July 2020 but is on extended support until June 2022.

@mattab Are we ok or not ok to drop support on Debian 9 and more forward with Debian 10 only?

Reference:
https://en.wikipedia.org/wiki/Debian_version_history#Release_table

**Comment by aureq** [comment] 2020-12-04 12:20
@anoma in case you wish to follow this thread.

**Comment by Findus23** [comment] 2020-12-04 13:03
I guess Debian 9 with a modern PHP version from https://deb.sury.org/ should also work.

**Comment by aureq** [comment] 2020-12-04 15:40
Yes it should work.

However, I should point the following considerations:

- package names may be different and will add some complexity in our own. I haven't investigated this aspect.
- for production environment, teams may look at the security(*) of the 3rd party repositories like Sury (it seems to be a single developer)

While alternatives are possible (yeah!), that doesn't answer the question of either we are dropping support for Debian 9 and below.

(*) I'm not saying it's not secure, I'm saying that company guidelines may not welcome unofficial repositories in their environment.

**Comment by anoma** [comment] 2020-12-04 23:40
In a perfect world we would support Debian 9 with a more modern PHP but in that world we would also have to support Debian 10.

So that would be

- Matomo V3 on Debian 9
- Matomo V4 on Debian 9
- Matomo V3 on Debian 10
- Matomo V4 on Debian 10

It is not for me to say but this feels like too much, too many variables, especially when we have essentially made a special Matomo specific Debian 9 as part of it.

I hate to say but I would suggest announcing EOL of Debian 9 to coincide with EOL for Matomo v3. Dont support Matomo v4 on Debian 9 at all and update all documentation to ensure all new installs couple Matomo v4 with Debian 10.

That give everyone 11 months to plan a EOL upgrade and early adopters can move early.

**Comment by anoma** [comment] 2021-03-12 11:15
I have been on other things recently but it occurs to me that I dont think I have seen a Matomo update or an addon update for V3 in what feels like weeks maybe months.

Are we at the point now that V3 is essentially hibernating even addons? 

Does this focus our mind to deal with V4 path?

**Comment by anoma** [comment] 2021-06-23 07:47
Polite bump. I just attempted a Debian 9 > 10 upgrade of a Matomo box and it went spectacularly badly.

Has V4.X seen any movement? I ask because I dont want to put a lot of effort into fixing this here if the best end result is 
Matomo 3.14.1 (10 months out of date).

No malice but I am running out of excuses why my users see all these EOL notes and are getting no addon updates. Whilst I dont want to, at some point I have to cut my losses and jump to a manual install.

Please tell me I dont have to do this :)

**Comment by glatzenarsch** [comment] 2021-07-07 12:56
Greetings,

what is with official Matomo debian repository (http://debian.matomo.org/), latest available release is 3.14. Can we add https://builds.matomo.org/ in repo list and use it safely?!

Thanks in advance

**Comment by Findus23** [comment] 2021-07-07 13:44
Hi,

https://builds.matomo.org/ is not a Debian repository, but the collection of all official Matomo builds for every version released yet.

**Comment by nomandera** [comment] 2021-07-13 14:29
So to add some specifics

https://debian.matomo.org/dists/piwik/main/binary-amd64/Packages

includes:


```
Package: matomo
Version: 3.14.1-2
Architecture: all
Maintainer: Aurelien Requiem <aurelien@requiem.fr>
Installed-Size: 56245
Pre-Depends: debconf (>= 0.5.00) | debconf-2.0
Depends: php5-cli (>= 5.5.9) | php-cli, php5-mysql | php5-mysqlnd | php-mysql | php-mysqlnd, php5-curl | php-curl, php5-gd | php-gd, php5-cli | php-mbstring, php5-cli | php-simplexml
Recommends: logrotate, libapache2-mod-php5 (>= 5.3.3) | php5-cgi (>= 5.5.9) | php5-fpm (>= 5.5.9) | libapache2-mod-php | php-cgi | php-fpm, php5-geoip | php-geoip
Suggests: mariadb-server | mysql-server, geoip-database-extra, php-mbstring, libmaxminddb0
Homepage: http://matomo.org
Priority: optional
Section: web
Filename: pool/main/m/matomo/matomo_3.14.1-2_all.deb
Size: 12361776
SHA256: 841d0913236bb6d033b5aa619c8c9f091873c1f6a0279349c0eeff7b49d9394e
SHA1: ca6ec5eae0c932315454a296c5e0872526834615
MD5sum: 377c053693b915370f720f07f47afbc4
Description: Leading Free/Libre open source Web Analytics software
 Matomo (formerly Piwik) is a full featured PHP MySQL software program that
 you download and install on your own webserver. At the end of the five minute
 installation process you will be given a JavaScript code. Simply copy and
 paste this tag on websites you wish to track and access your analytics reports
 in real time.
```

If you perform an inline upgrade of Debian 9 to 10 following normal recommended procedures these dependencies fail quite spectacularly at the final clean-up phase which removes the hold on:

```
The following packages have been kept back:
  apache2 apache2-bin apache2-data apache2-utils curl libdbd-mysql-perl libdbi-perl libfcgi-perl libhtml-parser-perl liblocale-gettext-perl libterm-readkey-perl libtext-charwidth-perl libtext-iconv-perl
  mariadb-server perl perl-base php-geoip php-igbinary php-mbstring php-mysql php-redis php-xml rename
```

and in detail does the following:

```
# apt full-upgrade
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Calculating upgrade... Done
The following packages were automatically installed and are no longer required:
  apache2 apache2-bin apache2-data apache2-utils fontconfig-config fonts-dejavu-core libapache2-mod-php7.0 libapr1 libaprutil1 libaprutil1-dbd-sqlite3 libaprutil1-ldap libbrotli1 libfontconfig1 libgd3 libjbig0
  libjemalloc1 libjpeg62-turbo liblua5.2-0 libperl5.24 libtiff5 libwebp6 libxpm4 php-geoip php-mysql php7.0-cli php7.0-gd php7.0-json php7.0-mbstring php7.0-mysql php7.0-opcache php7.0-xml php7.3-mysql rename
  ssl-cert
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  libcurl3 libmariadbclient18 mariadb-client-10.1 mariadb-client-core-10.1 mariadb-server-10.1 mariadb-server-core-10.1 matomo php7.0-curl piwik
The following NEW packages will be installed:
  libbrotli1 libcurl4 libgdbm-compat4 libmariadb3 libperl5.28 libsnappy1v5 libsodium23 mariadb-client-10.3 mariadb-client-core-10.3 mariadb-server-10.3 mariadb-server-core-10.3 perl-modules-5.28 php7.3-cli
  php7.3-common php7.3-json php7.3-mbstring php7.3-mysql php7.3-opcache php7.3-phpdbg php7.3-readline php7.3-xml
The following packages will be upgraded:
  apache2 apache2-bin apache2-data apache2-utils curl libdbd-mysql-perl libdbi-perl libfcgi-perl libhtml-parser-perl liblocale-gettext-perl libterm-readkey-perl libtext-charwidth-perl libtext-iconv-perl
  mariadb-server perl perl-base php-geoip php-igbinary php-mbstring php-mysql php-redis php-xml rename
23 upgraded, 21 newly installed, 9 to remove and 0 not upgraded.
Need to get 35.0 MB of archives.
After this operation, 11.5 MB disk space will be freed.
```


You can stop here and you will have a partially upgraded system with more modern kernel and several hundred packages but the core Matomo/Apache/php elements will remain pinned to Debian 9 and Matomo will still operate albeit with all the PHP EOL warnings.

Obviously though this is risky. If any sysop makes a mistake and completes the upgrade Matamo stops working.

I am happy to do some more work on this to determine just how broken matomo becomes but I can't do it solo. I need developer support as end game requires repository fixes.

I realise these are trying times we live in and I am trying to be pragmatic but Debian 9 now fails security audits due to non extended EOL support so my hand is forced. I have to fix this I cant wait any longer.


Being slightly more dramatic, we committed to this approach due to 

https://matomo.org/blog/2014/04/piwik-debian-package/

> Will the debian repository be maintained in the future?
> 
> Yes, Aurélien Requiem (github) along with the Matomo team are committed to maintain the Debian Matomo repository in the future. 

but this seems to all be falling on @aureq shoulders. **Team Matomo where are you :)**


Note: I realise this is a V4 thread and the above is V3 centric but they go hand in hand. Everyone wants apt v4 and supporting Debian 10 is a crucial stepping stone

**Comment by Findus23** [comment] 2021-07-13 14:45
> Team Matomo where are you :)

At least from my point of few the issue is that while I am using Debian primarily for many years, I'm not that familiar with the packaging process.
Also in the end of the day, Matomo is just a bunch of PHP files and I never really felt the need to use a Debian package for it.
So I'm not to sure how I can help (apart from helping Debian beginners on how to get running with Matomo)

**Comment by nomandera** [comment] 2021-07-26 07:05
I do not recommend this as you will end up with a Dr Frankenstein install however if like me you must upgrade to Debian 10 and the choice is this or dropping Matomo you can:

`apt-mark hold apache2 matomo`

You can now proceed with `apt upgrade` which will result in:


```
The following packages have been kept back:
  apache2 apache2-bin apache2-data apache2-utils curl libdbd-mysql-perl libdbi-perl libfcgi-perl libhtml-parser-perl liblocale-gettext-perl libterm-readkey-perl libtext-charwidth-perl libtext-iconv-perl
  mariadb-server perl perl-base php-geoip php-igbinary php-mbstring php-mysql php-redis php-xml ren
```

End result is Debian 10, with Debian 9 levels of Apache, PHP and Matomo 3.14.1 (and all associated PHP warnings etc)

Or you can proceed with `apt full-upgrade` to complete your Debian 9 to 10 migration which will result in:

```
The following packages were automatically installed and are no longer required:
  dh-python libbind9-140 libdns162 libicu57 libisc160 libisccc140 libisccfg140 libjemalloc1 liblwres141 libmpfr4 libperl5.24 libpython3.5-minimal libpython3.5-stdlib libxerces-c3.1 libxml-security-c17v5
  linux-image-4.9.0-15-amd64 python3-distutils python3-lib2to3 python3.5 python3.5-minimal rename sgml-base tcpd xml-core
Use 'apt autoremove' to remove them.
The following packages will be REMOVED:
  libcurl3 libmariadbclient18 mariadb-client-10.1 mariadb-client-core-10.1 mariadb-server-10.1 mariadb-server-core-10.1 php7.0-curl
The following NEW packages will be installed:
  libcurl4 libgdbm-compat4 libmariadb3 libperl5.28 libsnappy1v5 libsodium23 mariadb-client-10.3 mariadb-client-core-10.3 mariadb-server-10.3 mariadb-server-core-10.3 perl-modules-5.28 php-curl php7.3-cli
  php7.3-common php7.3-curl php7.3-json php7.3-mbstring php7.3-mysql php7.3-opcache php7.3-phpdbg php7.3-readline php7.3-xml
The following packages have been kept back:
  apache2 apache2-bin apache2-data apache2-utils
The following packages will be upgraded:
  curl libdbd-mysql-perl libdbi-perl libfcgi-perl libhtml-parser-perl liblocale-gettext-perl libterm-readkey-perl libtext-charwidth-perl libtext-iconv-perl mariadb-server perl perl-base php-geoip php-igbinary
  php-mbstring php-mysql php-redis php-xml rename
19 upgraded, 22 newly installed, 7 to remove and 4 not upgraded.
Need to get 32.8 MB of archives.
```
End result is Debian 10, with Debian 9 levels of Apache and Matomo 3.14.1 (still with PHP warnings as Apache2 is tied to the still install 7.0 version - probably fixable) - i.e. the same as before but at least this way a rogue apt upgrade does not break the system.


@mattab @sgiehl ping (as you have contributed to the various apt threads in the past) by any chance do you have any insight into Matomo plans for this.

**Comment by mattab** [comment] 2021-08-30 18:41
Hello everyone, Thanks for your patience, let's continue the discussion in this other issue for now, where we're looking for a new maintainer for the debian package:  #131

**Comment by mattab** [comment] 2021-09-01 03:01
Let's continue the discussion in  #131 - if a new maintainer is keen to take over this, we can then reopen this issue. Thanks

**Closed by mattab** 2021-09-01 03:01 UTC
