### ISSUE TITLE
system check warning about readme file

### ISSUE THREAD

**Issue by ma2thieu** [matomo-org/matomo-package#82] opened 2018-09-16 16:20 UTC
System check gives warning about /usr/share/doc/matomo/README.md.gz : 
```
Files were found in your Matomo but we didn't expect them.
--> Please delete these files to prevent errors. <--

File to delete: README.md.gz

To delete all these files at once, you can run this command:
rm "/usr/share/doc/matomo/README.md.gz"
```
Also there is a dead link to ../doc/matomo/README.md which doesn't exist : 
```
lrwxrwxrwx  1 root     root       23 Jun 26 09:35 README.md -> ../doc/matomo/README.md
lrwxrwxrwx  1 root     root       26 Jun 26 09:35 README.md.gz -> ../doc/matomo/README.md.gz
```

**Comment by sgiehl** [comment] 2018-09-16 20:41
that file should not be included in Matomo at all. How did you install it? Was it maybe done using an automated installer of your hoster? Maybe that created this file.

**Comment by ma2thieu** [comment] 2018-09-17 08:47
This is a dedicated server (debian 9.5) and I installed it with `apt-get install matomo`
```
# /etc/apt/sources.list.d/matomo.list
deb http://debian.matomo.org/ piwik main
deb-src http://debian.matomo.org/ piwik main
```
```
dpkg -l | grep matomo
ii  matomo                                3.5.1-2                           all          Leading Free/Libre open source Web Analytics software
```

**Comment by sgiehl** [comment] 2018-09-17 08:52
maybe @aureq  is able to say more here

**Comment by mackuba** [comment] 2018-10-23 19:37
I'm having the same problem. It's just a warning, so it's not a serious issue, but it definitely exists. Could you reopen this?

I've installed the `matomo` package (3.5.1-2) from the http://debian.matomo.org repo on Ubuntu 14.04 LTS (here in a Virtualbox/Vagrant test box, but originally on my VPS and I had the same thing there).

<img width="629" alt="screenshot 2018-10-23 at 21 31 14" src="https://user-images.githubusercontent.com/28465/47385737-2c247900-d70b-11e8-8ae1-e6b441e8c7b2.png">

<img width="958" alt="screenshot 2018-10-23 at 21 31 26" src="https://user-images.githubusercontent.com/28465/47385810-50805580-d70b-11e8-8020-e5eec383eb15.png">

**Comment by Findus23** [comment] 2018-10-23 19:48
I can reproduce this by unpacking `http://debian.matomo.org/pool/main/m/matomo/matomo_3.5.1-2_all.deb`

![grafik](https://user-images.githubusercontent.com/6266037/47386494-11530400-d70d-11e8-9b68-fdd87af8f825.png)

**Comment by mackuba** [comment] 2018-10-23 19:51
Looks like it might be a duplicate of https://github.com/matomo-org/matomo-package/issues/56.

**Closed** 2018-10-23 19:54 UTC
